### ISSUE TITLE
Not sure if I have the right repo ? But implement "headers" on .devices.ubports.com/#/

### ISSUE THREAD

**Issue by 3rdwiki** [ubports/devices#1]
Just leave this here:

**We need** the "Active Devices", "Inprogress Devices", and "Voting Devices"

as 'Headers' so that we can say do the WebLink:

1, https://devices.ubports.com/#Active_Devices

2, https://devices.ubports.com/#Inprogress_Devices

3, https://devices.ubports.com/#Voting_Devices

(and the link goes to that 'section' of the devices.ubports.com/#/ web-page).

**Comment by UniversalSuperBox** [comment]
I've created a new issue on the correct repository. While I don't know how the devices.ubports.com website works, hopefully someone can take a look at it there.

Thank you for your patience.
